from __future__ import annotations

import json
import shutil
from pathlib import Path

from .runtime import ArtifactWriter, CommandRunner, HarnessError

# Cheapest Claude model — all harness Claude runs must use Haiku 4.5.
DEFAULT_CLAUDE_MODEL = "haiku"


class ClaudeEnvironment:
    """Provision an isolated-but-global-auth Claude launch for the AOE harness.

    Claude needs OAuth/keychain credentials, so we do NOT isolate the config dir
    (copying auth.json is insufficient). Instead we keep global auth and isolate
    only the parts that would otherwise pollute / mis-route:

      - hooks: `--setting-sources local` drops the global `user` settings
        (and its hooks), and `--settings <generated>` loads ONLY the harness
        synchronize hooks (generated by scripts/claude-hooks-config.ts → they
        point at the worktree CLI and are env-gated by SYNCHRONIZE_HOOK_ENABLE,
        resolving SYNCHRONIZE_HOME/SYNCHRONIZE_CLI at runtime → harness daemon).
      - MCP: `--mcp-config <generated> --strict-mcp-config` → only the worktree
        synchronize MCP, never the user's global servers.
      - session id: `--session-id <uuid>` pins the id so the resumed
        `claude --resume <id>` matches (Claude otherwise assigns it on the first
        message). Global ~/.claude/projects holds the transcript for both the
        original launch and the daemon's resume, so there is no session-dir
        mismatch (unlike Pi).
    """

    def __init__(self, repo: Path, sync_home: Path, config_dir: Path, model: str, writer: ArtifactWriter, runner: CommandRunner) -> None:
        self.repo = repo
        self.sync_home = sync_home
        self.config_dir = config_dir
        self.model = model
        self.writer = writer
        self.runner = runner
        self.settings_path = config_dir / "claude-settings.json"
        self.mcp_path = config_dir / "claude-mcp.json"

    # --- PiEnvironment-compatible interface (so the base scenario can swap us in) ---
    def validate(self) -> None:
        self.preflight()

    def install_package_command(self) -> list[str]:
        return ["true"]  # Claude needs no package install step.

    def cli(self) -> Path:
        return self.repo / "bin" / "synchronize"

    def mcp(self) -> Path:
        return self.repo / "bin" / "synchronize-mcp"

    def provision(self) -> None:
        self.config_dir.mkdir(parents=True, exist_ok=True)
        # Isolated synchronize hooks generated by the repo's own tool, so the
        # command shape never drifts from production.
        self.settings_path.write_text("{}\n", encoding="utf-8")
        result = self.runner.run(
            ["bun", "run", str(self.repo / "scripts" / "claude-hooks-config.ts"), str(self.settings_path)],
            check=False,
            log_name="claude-hooks-config",
        )
        if result.returncode != 0:
            raise HarnessError(f"claude-hooks-config failed: {result.stderr or result.stdout}")
        # NOTE: do NOT inject a "tui" setting here — Claude validates --settings
        # and only accepts "default"/"fullscreen" (an invalid value makes Claude
        # offer to "fix" the config, derailing the session). The fullscreen /
        # alternate-screen renderer is disabled via the CLAUDE_CODE_DISABLE_
        # ALTERNATE_SCREEN=1 env var in command_for_session instead, so this
        # isolated settings file stays minimal (hooks only).
        # Isolated MCP: only the worktree synchronize server, routed to the
        # harness daemon via SYNCHRONIZE_HOME (Claude notification channel mode).
        mcp_config = {
            "mcpServers": {
                "synchronize": {
                    "command": str(self.mcp()),
                    "args": [],
                    "env": {
                        "SYNCHRONIZE_HOME": str(self.sync_home),
                        "SYNCHRONIZE_MCP_MODE": "claude",
                    },
                }
            }
        }
        self.mcp_path.write_text(f"{json.dumps(mcp_config, indent=2)}\n", encoding="utf-8")
        self.writer.write_json(
            "claude-env.json",
            {"settings": str(self.settings_path), "mcp_config": str(self.mcp_path), "model": self.model},
        )

    def preflight(self) -> None:
        if shutil.which("claude") is None:
            raise HarnessError("`claude` CLI is not installed")
        if not self.cli().exists():
            raise HarnessError(f"worktree synchronize CLI missing: {self.cli()}")

    def command_for_session(self, name: str) -> str:
        env_parts = {
            # Disable Claude's alternate-screen (fullscreen) renderer so output is
            # inline and tmux capture-pane can read the warmup/recall markers, and
            # the "try the fullscreen renderer?" prompt never blocks the session.
            "CLAUDE_CODE_DISABLE_ALTERNATE_SCREEN": "1",
            "SYNCHRONIZE_HOOK_ENABLE": "1",
            "SYNCHRONIZE_HOME": str(self.sync_home),
            "SYNCHRONIZE_CLI": str(self.cli()),
            "SYNCHRONIZE_MCP": str(self.mcp()),
            "SYNCHRONIZE_PORT": "0",
            "SYNCHRONIZE_SESSION_NAME": name,
        }
        command = ["env"]
        for key, value in env_parts.items():
            command.append(f"{key}={value}")
        command.extend(
            [
                "claude",
                "--dangerously-skip-permissions",
                # Match the real product launch: register the synchronize MCP as a
                # live push channel (server: channels only load as a development
                # channel). Triggers a one-time confirm prompt that the harness
                # auto-dismisses with Enter after launch.
                "--dangerously-load-development-channels",
                "server:synchronize",
                "--setting-sources",
                "local",
                "--settings",
                str(self.settings_path),
                "--mcp-config",
                str(self.mcp_path),
                "--strict-mcp-config",
                "--model",
                self.model,
            ]
        )
        return " ".join(_shell_quote(token) for token in command)


def _shell_quote(token: str) -> str:
    safe = all(c.isalnum() or c in "_./:=-" for c in token)
    if safe and token:
        return token
    return "'" + token.replace("'", "'\\''") + "'"
