// Generated by web/scripts/generate-theme-registry.mjs. Do not edit by hand.

export const LIGHT_THEMES = ["light","rose-pine-dawn"] as const;
export const DARK_THEMES = ["kanagawa-wave"] as const;
export const ALL_THEMES = ["light","kanagawa-wave","rose-pine-dawn"] as const;
export const ALL_SKINS = ["brutal","glass"] as const;

export type ThemeName = (typeof ALL_THEMES)[number];
export type SkinName = (typeof ALL_SKINS)[number];

export const DEFAULT_LIGHT_THEME: ThemeName = "light";
export const DEFAULT_DARK_THEME: ThemeName = "kanagawa-wave";
export const INITIAL_THEME: ThemeName = "kanagawa-wave";
export const INITIAL_SKIN: SkinName = "glass";

export const THEME_OPTIONS = [
  {
    "value": "light",
    "title": "Light"
  },
  {
    "value": "kanagawa-wave",
    "title": "Kanagawa Wave"
  },
  {
    "value": "rose-pine-dawn",
    "title": "Rose Pine Dawn"
  }
] as const;
export const SKIN_OPTIONS = [
  {
    "value": "brutal",
    "title": "Brutal"
  },
  {
    "value": "glass",
    "title": "Glass"
  }
] as const;

const LEGACY_THEME_NORMALIZATION: Record<string, ThemeName> = {
  "catppuccin-mocha": "kanagawa-wave",
  "dark": "kanagawa-wave",
};

export function isThemeName(value: string | null): value is ThemeName {
  return ALL_THEMES.includes(value as ThemeName);
}

export function isSkinName(value: string | null): value is SkinName {
  return ALL_SKINS.includes(value as SkinName);
}

export function normalizeStoredTheme(value: string | null): ThemeName {
  if (value && LEGACY_THEME_NORMALIZATION[value]) return LEGACY_THEME_NORMALIZATION[value];
  return isThemeName(value) ? value : INITIAL_THEME;
}

export function normalizeStoredSkin(value: string | null): SkinName {
  return isSkinName(value) ? value : INITIAL_SKIN;
}
