// Generated by web/scripts/generate-theme-registry.mjs. Do not edit by hand.

export const LIGHT_THEMES = ["sigil-light"] as const;
export const DARK_THEMES = ["sigil-dark"] as const;
export const ALL_THEMES = ["sigil-light","sigil-dark"] as const;
export const ALL_SKINS = ["sigil"] as const;

export type ThemeName = (typeof ALL_THEMES)[number];
export type SkinName = (typeof ALL_SKINS)[number];

export const DEFAULT_LIGHT_THEME: ThemeName = "sigil-light";
export const DEFAULT_DARK_THEME: ThemeName = "sigil-dark";
export const INITIAL_THEME: ThemeName = "sigil-dark";
export const INITIAL_SKIN: SkinName = "sigil";

export const THEME_OPTIONS = [
  {
    "value": "sigil-light",
    "title": "Light"
  },
  {
    "value": "sigil-dark",
    "title": "Dark"
  }
] as const;
export const SKIN_OPTIONS = [
  {
    "value": "sigil",
    "title": "Sigil"
  }
] as const;

const LEGACY_THEME_NORMALIZATION: Record<string, ThemeName> = {
  "catppuccin-mocha": "sigil-dark",
  "dark": "sigil-dark",
  "kanagawa-wave": "sigil-dark",
  "light": "sigil-light",
  "rose-pine-dawn": "sigil-light",
};

export function isThemeName(value: string | null): value is ThemeName {
  return ALL_THEMES.includes(value as ThemeName);
}

export function isSkinName(value: string | null): value is SkinName {
  return ALL_SKINS.includes(value as SkinName);
}

export function normalizeStoredTheme(value: string | null): ThemeName {
  if (value && LEGACY_THEME_NORMALIZATION[value]) return LEGACY_THEME_NORMALIZATION[value];
  return isThemeName(value) ? value : INITIAL_THEME;
}

export function normalizeStoredSkin(value: string | null): SkinName {
  return isSkinName(value) ? value : INITIAL_SKIN;
}
